# Generated by Django 5.0.1 on 2024-05-06 16:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.IntegerField(choices=[(1, 'Herramientas Manuales'), (2, 'Materiales Basicos'), (3, 'Equipo de Seguridad'), (4, 'Tornillos y Anclajes'), (5, 'Fijaciones y Adhesivos'), (6, 'Equipos de Medicion')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)])),
                ('stock', models.IntegerField()),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoproducto')),
            ],
        ),
    ]
